"""
constants.py — Enumerations for the cloning platform.
"""
from enum import Enum


class EnvironmentStatus(str, Enum):
    PENDING = "PENDING"
    STARTED = "STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    ACTIVE = "ACTIVE"
    FAILED = "FAILED"
    ROLLED_BACK = "ROLLED_BACK"


class ResourceStatus(str, Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    DONE = "DONE"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class ResourceType(str, Enum):
    IAM_ROLE = "IAM_ROLE"
    DYNAMODB_TABLE = "DYNAMODB_TABLE"
    SECRET = "SECRET"
    COGNITO_USER_POOL = "COGNITO_USER_POOL"
    COGNITO_APP_CLIENT = "COGNITO_APP_CLIENT"
    LAMBDA_FUNCTION = "LAMBDA_FUNCTION"
    API_GATEWAY = "API_GATEWAY"
    APPSYNC_API = "APPSYNC_API"
    AMPLIFY_BRANCH = "AMPLIFY_BRANCH"


class ProvisionStep(str, Enum):
    VALIDATE_SUBSCRIBER = "VALIDATE_SUBSCRIBER"
    PROVISION_IAM = "PROVISION_IAM"
    PROVISION_DYNAMODB = "PROVISION_DYNAMODB"
    PROVISION_SECRETS = "PROVISION_SECRETS"
    PROVISION_COGNITO = "PROVISION_COGNITO"
    PROVISION_LAMBDA = "PROVISION_LAMBDA"
    PROVISION_API_GATEWAY = "PROVISION_API_GATEWAY"
    PROVISION_APPSYNC = "PROVISION_APPSYNC"
    PROVISION_AMPLIFY = "PROVISION_AMPLIFY"
    HEALTH_CHECK = "HEALTH_CHECK"
    MARK_ACTIVE = "MARK_ACTIVE"
